Mixed precision batchnorm fix
Currently, if BN such as SyncBN is used in model with FSDP mixed precision enabled, auto wrapping will produce the following error:

```
RuntimeError: Expected counts to have type Half but got Float
```

the root cause being in this case that SyncBN kernels seems to assume fp32 somewhere and crashes for fp16 inputs.

Long term solution might be to make all BN kernels support fp16 / reduced precision types, but FSDP also supports other precision such as bloat16.

As a result, this PR fixes the issue by disabling mixed precision for BN units. To do this, we:

1. Add a policy that always wraps batchnorm layers in their own FSDP unit
2. Add a notion of "or policy" which returns True if either policy A or policy B fires
3. Use this in FSDP, where if mixed precision is enabled and model has BN, we `or` the given auto_wrap_policy with the policy that always wraps BN in its own unit. This works because children modules are always wrapped first, so recursive wrapping will go to leaf BN units and always wrap those.
4. Add an attribute to module `_wrap_override` that turns mixed precision off in FSDP config.

Differential Revision: [D36032761](https://our.internmc.facebook.com/intern/diff/D36032761/)

**NOTE FOR REVIEWERS**: This PR has internal Facebook specific changes or comments, please review them on [Phabricator](https://our.internmc.facebook.com/intern/diff/D36032761/)!

ghstack-source-id: 155203995
Pull Request resolved: https://github.com/pytorch/pytorch/pull/76642